return {
  {
    "LazyVim/LazyVim",
    opts = function()
      return {
        colorscheme = require("config.colorscheme").get(),
      }
    end,
  },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "mocha",
      transparent_background = true,
      term_colors = true,
      dim_inactive = {
        enabled = false,
      },
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        keywords = { "italic" },
      },
      custom_highlights = function(colors)
        return {
          Normal = { bg = "NONE" },
          NormalNC = { bg = "NONE" },
          NormalFloat = { bg = colors.mantle },
          FloatBorder = { bg = colors.mantle, fg = colors.surface2 },
          FloatTitle = { bg = colors.mantle, fg = colors.peach, bold = true },
          SignColumn = { bg = "NONE" },
          EndOfBuffer = { bg = "NONE" },
          StatusLine = { bg = "NONE" },
          StatusLineNC = { bg = "NONE" },
          CursorLine = { bg = "NONE" },
          CursorLineNr = { fg = colors.peach, bold = true },
          Visual = { bg = colors.surface1 },
          Search = { fg = colors.base, bg = colors.peach },
          IncSearch = { fg = colors.base, bg = colors.peach },
          Pmenu = { bg = colors.mantle },
          PmenuSel = { fg = colors.base, bg = colors.peach, bold = true },
          DashboardHeader = { fg = colors.peach, bold = true },
          DashboardIcon = { fg = colors.peach },
          DashboardCenter = { fg = colors.subtext1 },
          DashboardShortcut = { fg = colors.peach, bold = true },
          DashboardFooter = { fg = colors.overlay1, italic = true },
          CursorHidden = { bg = colors.base, blend = 100 },
          lCursorHidden = { bg = colors.base, blend = 100 },
          TelescopeNormal = { bg = colors.mantle },
          TelescopeBorder = { bg = colors.mantle, fg = colors.surface2 },
          TelescopeTitle = { bg = colors.mantle, fg = colors.peach, bold = true },
          TelescopePromptNormal = { bg = colors.mantle },
          TelescopePromptBorder = { bg = colors.mantle, fg = colors.surface2 },
          TelescopeResultsNormal = { bg = colors.mantle },
          TelescopeResultsBorder = { bg = colors.mantle, fg = colors.surface2 },
          TelescopePreviewNormal = { bg = colors.mantle },
          TelescopePreviewBorder = { bg = colors.mantle, fg = colors.surface2 },
          LazyNormal = { bg = colors.mantle },
          MasonNormal = { bg = colors.mantle },
          NoiceCmdlinePopup = { bg = colors.mantle },
          NoiceCmdlinePopupBorder = { bg = colors.mantle, fg = colors.surface2 },
          NoicePopup = { bg = colors.mantle },
          NoicePopupBorder = { bg = colors.mantle, fg = colors.surface2 },
          NeoTreeFileName = { fg = colors.text },
          NeoTreeFileIcon = { fg = colors.peach },
          NeoTreeDirectoryIcon = { fg = colors.yellow },
          NeoTreeDirectoryName = { fg = colors.yellow, bold = true },
          NeoTreeRootName = { fg = colors.peach, bold = true },
          NeoTreeModified = { fg = colors.peach, italic = true },
          NeoTreeGitAdded = { fg = colors.peach },
          NeoTreeGitDeleted = { fg = colors.peach },
          NeoTreeGitModified = { fg = colors.peach },
          NeoTreeGitRenamed = { fg = colors.peach },
          NeoTreeGitUntracked = { fg = colors.peach },
          NeoTreeGitIgnored = { fg = colors.peach },
          NeoTreeGitConflict = { fg = colors.peach, bold = true },
          Directory = { fg = colors.yellow, bold = true },
          ["@property"] = { fg = colors.teal },
          ["@variable"] = { fg = colors.text },
          ["@variable.builtin"] = { fg = colors.red, italic = true },
          ["@constant"] = { fg = colors.peach },
          ["@constant.builtin"] = { fg = colors.peach, italic = true },
          ["@string"] = { fg = colors.green },
          ["@string.escape"] = { fg = colors.pink },
          ["@number"] = { fg = colors.peach },
          ["@boolean"] = { fg = colors.peach, italic = true },
          ["@keyword"] = { fg = colors.mauve, italic = true },
          ["@keyword.return"] = { fg = colors.red, italic = true },
          ["@operator"] = { fg = colors.sky },
          ["@type"] = { fg = colors.yellow },
          ["@type.builtin"] = { fg = colors.yellow, italic = true },
          ["@function"] = { fg = colors.blue },
          ["@function.builtin"] = { fg = colors.blue, italic = true },
          ["@function.method"] = { fg = colors.sapphire },
          ["@constructor"] = { fg = colors.lavender },
          ["@punctuation.bracket"] = { fg = colors.overlay2 },
          ["@punctuation.delimiter"] = { fg = colors.overlay1 },
          ["@tag"] = { fg = colors.peach },
          ["@tag.attribute"] = { fg = colors.teal },
          ["@module"] = { fg = colors.yellow },
          ["@comment"] = { fg = colors.overlay1, italic = true },
          RainbowDelimiterBlue = { fg = colors.blue },
          RainbowDelimiterLavender = { fg = colors.lavender },
          RainbowDelimiterSapphire = { fg = colors.sapphire },
          RainbowDelimiterPeach = { fg = colors.peach },
          RainbowDelimiterGreen = { fg = colors.green },
          RainbowDelimiterYellow = { fg = colors.yellow },
        }
      end,
      integrations = {
        blink_cmp = true,
        dashboard = true,
        flash = true,
        gitsigns = true,
        mason = true,
        mini = true,
        native_lsp = {
          enabled = true,
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
        neotree = true,
        noice = true,
        notify = true,
        snacks = true,
        telescope = true,
        treesitter = true,
        treesitter_context = true,
        which_key = true,
      },
    },
    specs = {
      {
        "akinsho/bufferline.nvim",
        optional = true,
        opts = function(_, opts)
          if (vim.g.colors_name or ""):find("catppuccin") then
            opts.highlights = require("catppuccin.special.bufferline").get_theme()
          end
        end,
      },
    },
  },
}
